# Generated by Django 3.1.5 on 2021-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
