# Generated by Django 3.1.5 on 2021-01-27 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20210127_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friended_by',
            field=models.ManyToManyField(blank=True, related_name='friended_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
